<a href="https://colab.research.google.com/github/Marianderita/ML_Practice/blob/main/HW7_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [ ]:
import numpy as np

In [46]:
array_1 = np.array([5, 15, 25, 35, 45])
print(array_1)

array_2 = np.zeros([7,])
print(array_2)

array_3 = np.ones([6,])
print(array_3)

array_4 = np.arange(10, 20)
print(array_4)

[ 5 15 25 35 45]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19]



---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [20]:
data_original = np.array([12, 24, 36, 48, 60])

In [47]:
print(f"Оригінальний масив: {data_original}")

step_1 = data_original * 2
print(step_1)

step_2 = data_original + 10
print(step_2)

step_3 = data_original ** 2
print(step_3)

np.set_printoptions(precision=3, suppress=True)
step_4 = data_original ** 0.5
print(step_4)

Оригінальний масив: [12 24 36 48 60]
[ 24  48  72  96 120]
[22 34 46 58 70]
[ 144  576 1296 2304 3600]
[3.464 4.899 6.    6.928 7.746]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [22]:
data = np.array([18, 27, 33, 41, 52, 68, 79])

In [25]:
print(f"Середнє значення: {np.mean(data)}")
print(f"Мінімум: {np.min(data)}")
print(f"Максимум: {np.max(data)}")
print(f"Суму всіх елементів: {np.sum(data)}")

Середнє значення: 45.42857142857143
Мінімум: 18
Максимум: 79
Суму всіх елементів: 318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [26]:
arr = np.array([15, 22, 35, 44, 58, 67])

In [33]:
print(f"Перший елемент: {arr[0]}")
print(f"Останній елемент: {arr[-1]}")
print(f"Елементи з індексами 1 до 3: {arr[1:3]}")
print(f"Елементи більші за 40: {arr[arr > 40]}")

Перший елемент: 15
Останній елемент: 67
Елементи з індексами 1 до 3: [22 35]
Елементи більші за 40: [44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [34]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [44]:
print(f"Форма матриці: {np.shape(matrix)}")
print(f"Перший рядок: {matrix[0,]}")
print(f"Друга колонка: {matrix[:,1]}")
print(f"Сума всіх елементів: {matrix.sum()}")
print(f"Середнє: {matrix.mean()}")

Форма матриці: (3, 3)
Перший рядок: [2 4 6]
Друга колонка: [ 4 10 16]
Сума всіх елементів: 90
Середнє: 10.0
